# Generated by Django 5.1.7 on 2025-05-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='second_image',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
