# Generated by Django 5.1.7 on 2025-05-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0002_advertisement_second_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisements/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
