# Generated by Django 5.1.7 on 2025-05-21 06:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0003_alter_advertisement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
