# Generated by Django 5.0.6 on 2025-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0005_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.FileField(upload_to='advertisements/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='second_image',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
