# Generated by Django 5.0.6 on 2025-05-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adds', '0006_alter_advertisement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.FileField(upload_to='Eurotrip/advertisements/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='second_image',
            field=models.FileField(blank=True, null=True, upload_to='Eurotrip/advertisements/'),
        ),
    ]
