# Generated by Django 5.1.7 on 2025-03-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_category_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text="The user's interests", to='User.category'),
        ),
    ]
