# Generated by Django 5.1.7 on 2025-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_usersavedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedplace',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
