# Generated by Django 5.0.6 on 2025-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_usersavedplace_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, help_text="User's profile image", null=True, upload_to='Eurotrip/users/'),
        ),
    ]
