# Generated by Django 5.0.6 on 2025-05-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', help_text="The user's preferred language. Defaults to 'en' (English).", max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
