# Generated by Django 5.0.6 on 2025-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_language_user_notification_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
