# Generated by Django 5.0.6 on 2025-06-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_user_is_active_verificationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedplace',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
